### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by aodhgan** [Giftbit/stripe-stateful-mock#6]
getting an Error: : Cannot find module '/Users/user/stripeMockServer/stripe-stateful-mock'

Steps:
1. Created new directory and cd' in
2. npm init -y
3. npm add stripe-stateful-mock --save
4. npm install
5. node stripe-stateful-mock  --> gives error

**Comment by pushplay** [comment]
Hmm yeah it should have a bin file to be easy to start.  In the meantime start it with `node ./node_modules/stripe-stateful-mock` as a workaround.

**Comment by pushplay** [comment]
Fixed in https://github.com/Giftbit/stripe-stateful-mock/releases/tag/v0.0.12 with new instructions.
